name: football_live_app
description: A Flutter application that integrates with the API-Football REST API to display live soccer/football match data, statistics, and results.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  provider: ^6.1.1
  
  # Network
  dio: ^5.4.0
  http: ^1.1.2
  internet_connection_checker: ^3.0.1
  
  # Local Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  cached_network_image: ^3.3.1
  
  # Authentication
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.6
  
  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  intl: ^0.19.0
  flutter_native_splash: ^2.3.7
  
  # Utils
  get_it: ^8.0.3
  injectable: ^2.3.2
  logger: ^2.0.2+1
  connectivity_plus: ^6.1.4
  rxdart: ^0.28.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.5
  json_annotation: ^4.8.0
  
  # For web views
  webview_flutter: ^4.4.2

  #preview
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.1
  mockito: ^5.4.3
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/